(grades = sample(c('A','B','C','D'), size=30, replace=T, prob=c(.4,.3,.2,.1)))
summary(grades)
gradesf = factor (grades)
summary(gradesf)
table(grades)
table(gradesf)
class(gradesf)
(gradesf0 = factor(grades, ordered = T))
(gradesf01 = factor(grades, ordered = T, levels = c('B','C','A','D')))
summary(gradesf01)
(marks = ceiling( rnorm(30, mean = 60, sd =5)))
(student1 = data.frame( marks, gradesf01))
boxplot(marks ~ gradesf01, data = student1)
